#!/bin/bash
source assets/notice
docker_yum(){
       sudo yum install -y yum-utils \
           device-mapper-persistent-data \
           lvm2

        sudo yum-config-manager \
        --add-repo \
        http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
	sudo yum-config-manager --enable docker-ce-test
	yum makecache fast
	yum -y install docker-ce

	sudo sh ./assets/get-docker.sh --mirror Aliyun
	sudo systemctl enable docker	
	sudo systemctl start docker
	sudo groupadd docker
	sudo usermod -aG docker $USER
	sudo mkdir -p /etc/docker
	sudo echo '{"registry-mirrors": ["https://fw4bni9n.mirror.aliyuncs.com" ]}' > /etc/docker/daemon.json
	sudo systemctl daemon-reload
	sudo systemctl restart docker
	docker run hello-world
	
}

docker_apt(){
	while [ "$go" != 'y' ] && [ "$go" != 'n' ]
        do
        read -p "请确保版本不低于Ubuntu 16.04!(y/n) " go;
        done
        if [ "$go" == 'n' ];then
            exit
        fi
	sudo apt-get update
	sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
	 curl -fsSL https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository \
    "deb [arch=amd64] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
	sudo apt-get update
	sudo apt-get install docker-ce
	curl -fsSL get.docker.com -o get-docker.sh
	sudo sh get-docker.sh --mirror Aliyun
	sudo systemctl enable docker
	sudo systemctl start docker
	sudo groupadd docker
	sudo usermod -aG docker $USER
	docker run hello-world
	docker -v
}

yj_compose(){

	sudo gpasswd -a ${USER} docker
	cp assets/package/docker-compose /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
	green_info "${successInstall}"	

}

yj_lnmp(){
	sudo git clone https://gitee.com/meiyu1992/easylnmp www
	cp www/env.sample www/.env
	cp www/docker-compose.sample.yml www/docker-compose.yml
	cd www && docker-compose up -d
	host_name=`hostname`
	echo "访问地址:$host_name:80"
}
