#!/bin/bash

isCentos7="抱歉, 7.x不支持Centos6.x!"
isDockerInstall="docker没有安装,现在是否安装(y/n):"
currentVersion="当前版本:"
paramsError='error1:无效的参数,请使用"./yjscript --help"获取帮助';
portError="error:缺少端口号!"
noCompose="木有安装docker-compose,执行'./yjscript -compose'安装"
yjlnmpInstall="本功能适用于纯净的centos系统安装"
successInstall="安装成功"
red_error(){
          printf '\033[1;31;40m%b\033[0m\n' "$1";
         exit 0; 
}
blue_info(){
          printf '\033[36m%b\033[0m\n' "$1";
}           
green_info(){ 
          printf '\033[32m%b\033[0m\n' "$1";

}       


